export const engineAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_relayer", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "CADENCE_ARCH",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_ROUNDS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MOVE_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "READY_TIMEOUT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ROUND_TIMEOUT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createMatch",
    inputs: [{ name: "betAmount", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "joinMatch",
    inputs: [{ name: "matchId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "matches",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "player1", type: "address", internalType: "address" },
      { name: "player2", type: "address", internalType: "address" },
      { name: "challenger", type: "address", internalType: "address" },
      { name: "conman", type: "address", internalType: "address" },
      { name: "winner", type: "address", internalType: "address" },
      { name: "betAmount", type: "uint256", internalType: "uint256" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "readyDeadline", type: "uint256", internalType: "uint256" },
      { name: "currentRound", type: "uint256", internalType: "uint256" },
      { name: "player1Ready", type: "bool", internalType: "bool" },
      { name: "player2Ready", type: "bool", internalType: "bool" },
      { name: "status", type: "uint8", internalType: "enum Engine.Status" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ready",
    inputs: [{ name: "matchId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealMove",
    inputs: [
      { name: "matchId", type: "uint256", internalType: "uint256" },
      { name: "roundNumber", type: "uint256", internalType: "uint256" },
      { name: "move", type: "uint256", internalType: "uint256" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rounds",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "startTime", type: "uint256", internalType: "uint256" },
      { name: "conmanCommit", type: "bytes32", internalType: "bytes32" },
      { name: "challengerCommit", type: "bytes32", internalType: "bytes32" },
      { name: "conmanChoice", type: "uint256", internalType: "uint256" },
      { name: "challengerChoice", type: "uint256", internalType: "uint256" },
      { name: "conmanRevealed", type: "bool", internalType: "bool" },
      { name: "challengerRevealed", type: "bool", internalType: "bool" },
      { name: "resolved", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateRelayer",
    inputs: [{ name: "_relayer", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "MatchCreated",
    inputs: [
      {
        name: "matchId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "betAmount",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchJoined",
    inputs: [
      {
        name: "matchId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "joiner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchReady",
    inputs: [
      {
        name: "matchId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayersReady",
    inputs: [
      {
        name: "matchId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "challenger",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "conman",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundStarted",
    inputs: [
      {
        name: "matchId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "roundNumber",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "tilesCount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;
