import "@/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "../components/provider/rainbow-provider";

import Connect from "@/components/connect";


export const metadata: Metadata = {
  title: "Create Web3 Kit",
  description: "Generated by create-w3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
        <nav className="bg-black/10 dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b-3 border-black dark:border-gray-600">
        <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <div className="flex flexcol items-center justify-center mx-2">
            <img src="./logo.png" className="h-16 border-black border-3 rounded-full mx-3" alt="Pontoon Logo"/>
            <span className="text-2xl font-semibold dark:text-white mx-auto">Pontoon</span>
            </div>
          <div className="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <Connect />
          </div>
        </div>
      </nav>
          {children}
          
          </Providers>
      </body>
    </html>
  );
}
