import "@/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "../components/provider/rainbow-provider";

import Connect from "@/components/connect";

export const metadata: Metadata = {
  title: "Create Web3 Kit",
  description: "Generated by create-w3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.className}>
      <body>
        <Providers>
          <nav className="fixed start-0 top-0 z-20 w-full border-b-1 border-black bg-black/10 dark:border-gray-600 dark:bg-gray-900">
            <div className="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between p-4">
              <div className="flexcol mx-2 flex items-center justify-center">
                <img
                  src="./logo.png"
                  className="mx-3 h-16 rounded-full border-2 border-black"
                  alt="Pontoon Logo"
                />
                <span className="mx-auto text-2xl font-semibold dark:text-white">
                  Pontoon
                </span>
              </div>
              <div className="flex space-x-3 md:order-2 md:space-x-0 rtl:space-x-reverse">
                <Connect />
              </div>
            </div>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
